name: Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
        GOOGLE_SHEET_BOOK: ${{ secrets.GOOGLE_SHEET_BOOK }}
        GOOGLE_SHEET_GOVP: ${{ secrets.GOOGLE_SHEET_GOVP }}
        GOOGLE_SHEET_JUDI: ${{ secrets.GOOGLE_SHEET_JUDI }}
        GOOGLE_SHEET_PERO: ${{ secrets.GOOGLE_SHEET_PERO }}
        GOOGLE_SHEET_CREA: ${{ secrets.GOOGLE_SHEET_CREA }}
        GOOGLE_SHEET_GOVA: ${{ secrets.GOOGLE_SHEET_GOVA }}
        GOOGLE_SHEET_FOCUS: ${{ secrets.GOOGLE_SHEET_FOCUS }}
        GOOGLE_SHEET_AV: ${{ secrets.GOOGLE_SHEET_AV }}
        GOOGLE_SHEET_ELEC: ${{ secrets.GOOGLE_SHEET_ELEC }}
        GOOGLE_SHEET_OVSE: ${{ secrets.GOOGLE_SHEET_OVSE }}
        GOOGLE_SHEET_POPY: ${{ secrets.GOOGLE_SHEET_POPY }}
        GOOGLE_SHEET_LEGC: ${{ secrets.GOOGLE_SHEET_LEGC }}
        GOOGLE_SHEET_COMM: ${{ secrets.GOOGLE_SHEET_COMM }}
        GOOGLE_SHEET_NGO: ${{ secrets.GOOGLE_SHEET_NGO }}
      run: npm test